apiVersion: v1
kind: Service
metadata:
  name: demoapi
  namespace: demo
  labels:
    app: demoapi
spec:
  type: ClusterIP
  selector:
    app: demoapi
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
