---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapi
  namespace: demo
  labels:
    app: demoapi
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.init: regex:^3.10.*
    fluxcd.io/tag.podinfod: semver:~3.1
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: demoapi
  template:
    metadata:      
      labels:
        app: demoapi
   spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux 
      containers:
      - name: demoapisample
        image: 654698825315.dkr.ecr.us-east-1.amazonaws.com/sample/demoapi:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        ports:
          - name: http
            containerPort: 80          
        